name: Build TrollStore tvOS IPA

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Patch Makefile to remove missing includes
        run: |
          sed -i '' '/\/makefiles\/common.mk/d' Makefile
          sed -i '' '/\/tool.mk/d' Makefile

      - name: Show Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build using Makefile
        run: make

      - name: Find and list IPA files
        run: |
          ls -lh ./_build/*.ipa || echo "No IPA files found."

      - name: Upload IPA artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore-ipa
          path: ./_build/*.ipa
